### PR TITLE
025/logging service

### PR DESCRIPTION
**Pull request by psyak10**
Creates the logging service

### CODE REVIEW

**Comment by micalexis** [comment]
Looks good to me! can you please squash your commits?

**Comment by psyak10** [comment]
> Looks good to me! can you please squash your commits?

Is this all good now?

**Comment by micalexis** [comment]
fix the commit message then you are all good!

**Comment by psyak10** [comment]
> fix the commit message then you are all good!

What do you mean? / How?

**Comment by psyak10** [comment]
> > fix the commit message then you are all good!
> 
> What do you mean? / How?

**Comment by psyak10** [comment]
> fix the commit message then you are all good!

Is this now good? haha

**Pull request merged**
